name: Test & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1053'
      - name: Cache All The Things
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Test and Build
        run: clojure -T:build ci :snapshot false
      - name: Deploy Release
        run: clojure -T:build deploy :snapshot false
        env:
          CLOJARS_PASSWORD: ${{secrets.DEPLOY_TOKEN}}
          CLOJARS_USERNAME: ${{secrets.DEPLOY_USERNAME}}
